# 向量

使用 arange 函数创建一个向量（即一维的NumPy数组）：

In [1]:
import numpy as np
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [16]:
a.dtype

dtype('int64')

In [17]:
a.shape

(5,)

这是一个包含5个元素的向量，取值分别为0～4的整数。数组的数组类型是 int64，数组的 shape 属性返回一个元组（tuple）。
### 创建多维数组

In [11]:
m = np.array([np.arange(2), np.arange(2)])
m

array([[0, 1],
       [0, 1]])

In [13]:
m.shape

(2, 2)

In [25]:
m_3d = np.array([np.arange(3), np.arange(3), np.arange(3)])
m_3d

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [26]:
m_3d.shape

(3, 3)

## 选取数组元素

In [43]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

在创建这个多维数组时，我们给array函数传递的对象是一个嵌套的列表。现在来依次选取该数组中的元素。记住，数组的下标是从0开始的。

In [31]:
a[0,0]

1

In [32]:
a[0,1]

2

In [33]:
a[1,0]

3

In [34]:
a[1,1]

4

## NumPy 数据类型

| 类型 | 描述 |
| :- | :- |
| bool | 用一位存储的布尔类型（值为TRUE或FALSE） |
| inti | 由所在平台决定其精度的整数（一般为int32或int64）| 
| int8 | 整数，范围为128至127|
| int16 | 整数，范围为32 768至32 767 |
| int32 | 整数，范围为$-2^{31}$至$2^{31}-1$ |
| int64 | 整数，范围为263至263 1 |
| uint8 | 无符号整数，范围为0至255 |
| uint16 | 无符号整数，范围为0至65 535 |
| uint32 | 无符号整数，范围为0至2321 |
| uint64 | 无符号整数，范围为0至2641 |
| float16 | 半精度浮点数（16位）：其中用1位表示正负号， 5位表示指数， 10位表示尾数 | 
| float32 | 单精度浮点数（32位）：其中用1位表示正负号， 8位表示指数， 23位表示尾数 |
| float64或float | 双精度浮点数（64位）：其中用1位表示正负号， 11位表示指数， 52位表示尾数 | 
| complex64 | 复数，分别用两个32位浮点数表示实部和虚部 |
| complex128或complex | 复数，分别用两个64位浮点数表示实部和虚部 |

每一种数据类型均有对应的类型转换函数：

In [37]:
np.float64(42)

42.0

In [39]:
np.int8(42.0)

42

In [40]:
np.bool(42)

True

In [22]:
np.bool(0)

False

#### 数组的属性

In [20]:
b = np.array([np.arange(12), np.arange(12,24)])
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [16]:
b.ndim

1

In [21]:
b.size

24

# 2.10 分割数组 
## 水平分割

In [2]:
a = np.arange(9).reshape(3, 3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
np.hsplit(a, 3)

[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

In [8]:
np.split(a, 3, axis=1)

[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

# 垂直分割

In [9]:
np.vsplit(a, 3)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [12]:
np.split(a, 3, axis=0)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

## 深度分割

In [13]:
c = np.arange(27).reshape(3, 3, 3)
c

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [14]:
np.dsplit(c, 3)

[array([[[ 0],
         [ 3],
         [ 6]],
 
        [[ 9],
         [12],
         [15]],
 
        [[18],
         [21],
         [24]]]), array([[[ 1],
         [ 4],
         [ 7]],
 
        [[10],
         [13],
         [16]],
 
        [[19],
         [22],
         [25]]]), array([[[ 2],
         [ 5],
         [ 8]],
 
        [[11],
         [14],
         [17]],
 
        [[20],
         [23],
         [26]]])]