# 3.1 文件读写

In [1]:
import numpy as np

i2 = np.eye(2)
i2

array([[ 1.,  0.],
       [ 0.,  1.]])

In [2]:
np.savetxt('eye.txt', i2)

# 3.2 CSV 文件读写

CSV（Comma-Sperated Value，逗号分隔值）格式是一种常见的文件格式。通常，数据库的转存文件就是 CSV 格式的，文件中的各个字段对应于数据库表中的列。

In [3]:
c, v = np.loadtxt('data.csv', delimiter=',', usecols=(6, 7), unpack=True)

usecols的参数为一个元组，以获取第7字段至第8字段的数据，也就是股票的收盘价和成交量数据。unpack 参数设置为 True，意思是分拆存储不同列的数据，即分别将收盘价和成交量的数组赋值给变量 c 和 v。


In [5]:
c

array([ 336.1 ,  339.32,  345.03,  344.32,  343.44,  346.5 ,  351.88,
        355.2 ,  358.16,  354.54,  356.85,  359.18,  359.9 ,  363.13,
        358.3 ,  350.56,  338.61,  342.62,  342.88,  348.16,  353.21,
        349.31,  352.12,  359.56,  360.  ,  355.36,  355.76,  352.47,
        346.67,  351.99])

In [6]:
v

array([ 21144800.,  13473000.,  15236800.,   9242600.,  14064100.,
        11494200.,  17322100.,  13608500.,  17240800.,  33162400.,
        13127500.,  11086200.,  10149000.,  17184100.,  18949000.,
        29144500.,  31162200.,  23994700.,  17853500.,  13572000.,
        14395400.,  16290300.,  21521000.,  17885200.,  16188000.,
        19504300.,  12718000.,  16192700.,  18138800.,  16824200.])

# 3.3 计算成交量加权平均价格

In [7]:
vwap = np.average(c, weights=v)
vwap

350.58954935320088

vwap（Volume-Weighted Average Price，成交量加权平均价格）是一种经济学量，它代表着金融资产的“平均”价格。

## 3.3.1 算术平均值函数

In [9]:
mean = np.mean(c)
mean

351.03766666666672

## 3.3.2 时间加权平均价格

In [10]:
t = np.arange(len(c))
twap = np.average(c, weights=t)
twap

352.42832183908041

TWAP（Time-Weighted Average Price，时间加权平均价格）是另一种“平均”价格的指标。

# 3.4 最大值和最小值

In [12]:
h, l = np.loadtxt('data.csv', delimiter=',', usecols=(4, 5), unpack=True)
np.max(h)

364.89999999999998

In [13]:
np.min(l)

333.52999999999997

## 3.5 取值范围

In [14]:
np.ptp(h)

24.859999999999957