# 基础
## 创建矩阵
- 使用字符串创建矩阵

In [16]:
import numpy as np

A = np.mat('1 2 3; 4 5 6; 7 8 9')
A

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

- 使用 NumPy 数组创建矩阵

In [12]:
A = np.mat(np.arange(1,10).reshape(3, 3))
A

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

## 转置

In [13]:
A.T

matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

## 逆

In [14]:
A.I 

matrix([[  3.15251974e+15,  -6.30503948e+15,   3.15251974e+15],
        [ -6.30503948e+15,   1.26100790e+16,  -6.30503948e+15],
        [  3.15251974e+15,  -6.30503948e+15,   3.15251974e+15]])

# 从已有矩阵创建新矩阵
创建一个2*2的单位矩阵

In [17]:
A = np.eye(2)
A

array([[ 1.,  0.],
       [ 0.,  1.]])

创建另一个与 A 同型的矩阵，并乘以2:

In [19]:
B = 2 * A
B

array([[ 2.,  0.],
       [ 0.,  2.]])

使用字符串创建复合矩阵，该字符串的格式与 mat 函数中一致，只是在这里逆可以用矩阵变量名代替数字：

In [21]:
C = np.bmat('A B; A B')
C

matrix([[ 1.,  0.,  2.,  0.],
        [ 0.,  1.,  0.,  2.],
        [ 1.,  0.,  2.,  0.],
        [ 0.,  1.,  0.,  2.]])

## 填充

In [22]:
A = np.arange(4).reshape(2, 2)
A

array([[0, 1],
       [2, 3]])

In [27]:
B = np.zeros_like(A)
B

array([[0, 0],
       [0, 0]])

In [29]:
B = np.ones_like(A)
B

array([[1, 1],
       [1, 1]])

In [31]:
B = np.empty_like(A)
B

array([[-6917529027641081856, -3458755718422187075],
       [-6917529027641081854,      571745349544616]])

In [33]:
B = np.full_like(A, 9)
B

array([[9, 9],
       [9, 9]])

## 扁平迭代器
flat属性将返回一个flatiter对象，可以让我们像遍历一维数组一样遍历多维数组

In [35]:
A = np.arange(24).reshape(2,3,4)
A

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [36]:
A.flat[10]

10

获取多个元素  

In [37]:
A.flat[[1, 3, 5, 7, 9]]

array([1, 3, 5, 7, 9])

对flat属性赋值将导致整个数组的元素都被覆盖

In [39]:
A.flat = 9
A

array([[[9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9]],

       [[9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9]]])

指定元素进行覆盖

In [40]:
A.flat[[0, 2, 4, 6, 8]] = 0
A

array([[[0, 9, 0, 9],
        [0, 9, 0, 9],
        [0, 9, 9, 9]],

       [[9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9]]])

# 通用函数的方法

通用函数有四个方法：

- reduce

- accumulate

- reduceat

- outer

不过这些方法只对输入两个参数、输出一个参数的 ufunc 对象有效，例如 add 函数。其他不复合条件的 ufunc 对象调用这些方法时将抛出 ValueError 异常。 因此只能在二元通用函数上调用这些方法。

## reduce

沿着指定的轴，在连续的数组元素之间递归调用函数，即可得到输入数组的规约（reduce）计算结果。对于 add 函数，其对数组的 reduce 计算结果等价于对数组元素求和。

In [64]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [65]:
np.add.reduce(a)

36

## accumulate

同样可以递归作用于输入数组。单数与 reduce 方法不同的是，它将存储运算的中间结果并返回。因此在 add 函数上调用 accumulate 方法，等价于直接调用 cumsum 函数。

In [49]:
np.add.accumulate(a)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36])

## reduceat

reduceat 方法需要输入一个数组以及一个索引列表作为参数。

In [52]:
np.add.reduceat(a, [0, 5, 2, 7])

array([10,  5, 20, 15])

第一步用到索引值表中的0和5，实际上就是对数组中索引值在0到5之间的元素进行 reduce 操作。

In [55]:
np.add.reduce(a[0:5])

10

第二步用到索引值5和2。由于2比5小，所以直接返回索引值为5的元素

In [58]:
np.add.reduce(a[5])

5

第三步用到索引值2和7。

In [61]:
np.add.reduce(a[2:7])

20

第四步是对索引值从7开始知道数组末端的元素进行 reduce 操作：

In [63]:
np.add.reduce(a[7:])

15

## outer
outer 方法返回一个数组，它的秩（rank）等于两个输入数组的秩的和。

In [53]:
np.add.outer(np.arange(3), a)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [54]:
np.add.outer(np.arange(3), np.arange(2))

array([[0, 1],
       [1, 2],
       [2, 3]])